<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-28 14:47
=======
# Generated by Django 5.0.3 on 2024-03-28 02:30
>>>>>>> origin

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tag_lesson_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='courses.tag'),
        ),
    ]
